name: DevSecOps Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:

# ✅ 1. GITLEAKS (Secrets Scan)
  gitleaks:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install Gitleaks
        run: |
          go install github.com/gitleaks/gitleaks/v8@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Run Gitleaks Scan
        continue-on-error: true
        run: |
          gitleaks detect \
            --source . \
            --report-format json \
            --report-path=gitleaks-report.json

      - name: Upload Gitleaks Report
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json

        



# ✅ 2. TRIVY (Filesystem scan)
  trivy:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: Run Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          severity: 'CRITICAL,HIGH'


# ✅ 3. SONARCLOUD (Code Quality)
  sonar:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: [gitleaks, trivy]
    steps:
      - uses: actions/checkout@v3
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=skaftabuddin_devsecops-pipeline-demo
            -Dsonar.organization=skaftabuddin
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


# ✅ 4. ZAP (DAST Scan)
  zap_scan:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: sonar
    steps:
      - uses: actions/checkout@v3

      - name: Run ZAP Baseline
        continue-on-error: true
        run: |
          mkdir -p zap-output
          docker run --rm \
            -u root \
            -v $(pwd)/zap-output:/zap/wrk/:rw \
            zaproxy/zap-stable \
            zap-baseline.py \
            -t https://bookish-space-capybara-xpw9pppr974f475-3000.app.github.dev/#/ \
            -I \
            -r report.html

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-output/report.html
