name: Juice Shop Pipeline

on:
  workflow_dispatch:

jobs:
  dast-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Pipeline Started
        run: echo "Juice Shop Pipeline Running"
      
      - name: Run Nuclei Scan
        uses: projectdiscovery/nuclei-action@main
        with:
          target: https://devsecops-pipeline-demo.onrender.com
          flags: "-rl 5 -c 2 -severity low,medium"
