name: Juice Shop Pipeline

on:
  push:

jobs:
  dast-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Pipeline Started
        run: echo "Juice Shop Pipeline Running"
