name: OWASP ZAP Scan

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'https://bookish-space-capybara-xpw9pppr974f475-3000.app.github.dev/#/'
