name: OWASP ZAP Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run ZAP Baseline Scan
        run: |
          mkdir -p zap-output
          docker run --rm \
            -v $(pwd)/zap-output:/zap/wrk/:rw \
            zaproxy/zap-stable \
            zap-baseline.py \
            -t https://bookish-space-capybara-xpw9pppr974f475-3000.app.github.dev/#/ \
            -r report.html

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-output/report.html
